apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo40
  namespace: demo40
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo40
  template:
    metadata:
      labels:
        app: demo40
    spec:
      containers:
        - name: demo40
          image: 490529426410.dkr.ecr.us-east-1.amazonaws.com/demo40:ac7aabc28ed886f7780cb985d6dba4ab8d0f63e8
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_SERVICE_NAME
              value: "demo40"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.version=ac7aabc28ed886f7780cb985d6dba4ab8d0f63e8,deployment.environment=dev"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
