apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo14
  namespace: demo14
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo14
  template:
    metadata:
      labels:
        app: demo14
    spec:
      containers:
        - name: demo14
          image: 490529426410.dkr.ecr.us-east-1.amazonaws.com/demo14:pending
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_SERVICE_NAME
              value: "demo14"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.version=pending,deployment.environment=dev"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
