apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: 490529426410.dkr.ecr.us-east-1.amazonaws.com/demo-service:bd3fc0b573830e9bcdc7473d40aae9767b437817
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
