apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo8
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo8
  template:
    metadata:
      labels:
        app: demo8
    spec:
      containers:
        - name: demo8
          image: public.ecr.aws/docker/library/busybox:1.36
          command: ["sh", "-c", "sleep 3600"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
