apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: idp-applications
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/muthukannanmuruga/IDP-GitOps.git
        revision: main
        files:
          - path: apps/*/*/app.yaml
  template:
    metadata:
      name: '{{.name}}-{{.environment}}'
      namespace: argocd
      labels:
        idp.application: '{{.name}}'
        idp.environment: '{{.environment}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/muthukannanmuruga/IDP-GitOps.git
        targetRevision: main
        path: 'apps/{{.name}}/{{.environment}}'
      destination:
        name: '{{.cluster}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
