apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo11
  namespace: demo11
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo11
  template:
    metadata:
      labels:
        app: demo11
    spec:
      containers:
        - name: demo11
          image: public.ecr.aws/docker/library/busybox:1.36
          command: ["sh", "-c", "sleep 3600"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
